adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.users, name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

authnapp/urls.py
from django.urls import path

import mainapp.views as mainapp

import authnapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.views.static import serve

urlpatterns = [

    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact,name='contact'),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    path('auth/', include('authnapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin'))

]

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('<int:pk>/', mainapp.products, name='index'),
    path('product/<int:pk>/', mainapp.product, name='product'),

]

mainapp/models.py
from django.db import models


# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

mainapp/views.py
from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from .models import Product, ProductCategory

links_menu = [
    {'href': 'main', 'name': 'главная страница'},
    {'href': 'products:index', 'name': 'Продукция'},
    {'href': 'contact', 'name': 'контакты'},

]
same_products = [

]

def get_basket(user):
    basket_items = {}

    if user.is_authenticated:
        basket_items = Basket.objects.filter(user=user). \
            order_by('product__category')

    return basket_items

def main(request):
    content = {
        'titles': 'главная страница',
        'links_menu': links_menu,
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/index.html', context=content)


def index(request):
    content = {
        'titles': 'Продукты',
        'links_menu': links_menu,
        'category_menu': ProductCategory.objects.all(),
        'same_products': same_products,
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/products.html', context=content)


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'links_menu': links_menu,
        'category_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/product.html', content)


def products(request, pk=None):
    if (pk != None):
        products = Product.objects.filter(category_id=pk).all()
    else:
        products = Product.objects.all()
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    if pk:
        if pk == '0':
            products = Product.objects.all().order_by('price')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')
    content = {
        'titles': 'Продукты',
        'links_menu': links_menu,
        'category_menu': ProductCategory.objects.all(),
        'products': products,
        'basket': basket
    }
    return render(request, 'mainapp/products.html', context=content)


def contact(request):
    content = {
        'titles': 'Контакты',
        'links_menu': links_menu
    }
    return render(request, 'mainapp/contact.html', context=content)

templates/mainapp/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ titles|title }}{% endblock %}
{% block content %}
	<div class="container">
		<div class="hero">
			  {% include 'mainapp/menu.html' %}
			<h1>наши контакты</h1>
		</div>

		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

		<div class="clr"></div>
	</div>	

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}

templates/mainapp/inc_product.html
{% block product %}
<div class="block">
						<a href="#">
                            <img src="/media/{{ product.image }}" width="370" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>{{product.name}}</h4>

							</div>
						</a>
					</div>

templates/mainapp/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ titles|title }}{% endblock %}
{% block content %}
	<div class="container">
		<div class="slider">
			  {% include 'mainapp/menu.html' %}
			<div class="text-slider">
				<h3 class="green">  Текущая дата {% now "SHORT_DATETIME_FORMAT" %}</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
                <p>Текущая дата {% now "SHORT_DATETIME_FORMAT" %}</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png ' %}" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>

		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				<div class="block">
					<a href="#"><img src="{% static 'img/product-1.jpg' %}" alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="img">
							<h4>Отличный стул</h4>
							<p>Расположитесь комфортно. </p>
						</div> 
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/product-2.jpg' %}" alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>	
			</div>
		</div>
		
		<div class="clr"></div>

	</div>

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>	
{% endblock %}

templates/mainapp/menu.html
{% block menu %}
	<div class="header clearfix">
				<a href="{% url 'main' %}" class="logo"></a>
				<ul class="menu">

                {% for link in links_menu %}
                    <li>
                        <a href="{% url link.href %}"
                           class="{% if request.resolver_match.url_name == link.href %}
                                    active
                                  {% endif %}">
                            {{ link.name }}
                        </a>
                    </li>
                {% endfor %}
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'auth:edit' %}">
                        {{ user.first_name|default:'Пользователь' }}
                    </a>
                </li>
                {% endif %}
                  {% if user.is_superuser %}
                    <li>
                      <a href="{% url 'admin:users' %}">админка</a>
                    </li>
                  {% endif %}
                <li>
                    {% if user.is_authenticated %}
                      <a href="{% url 'auth:logout' %}">выйти</a>
                    {% else %}
                      <a href="{% url 'auth:login' %}">войти</a>
                    {% endif %}
                </li>
				</ul>
				<a href="#" class="search"></a>
                <a href="{% url 'basket:view' %}" class="basket">

                    <span style="color: red;font-weight: bold; margin-left: 30px;">
                         {% if basket %}
                              {{ basket.0.total_cost|floatformat:0 }} &#8381;
                              ({{ basket.0.total_quantity }} шт)
                         {% endif %}
                    </span>
                </a>

			</div>
{%  endblock %}

templates/mainapp/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
		<div class="hero-white">
			  {% include 'mainapp/menu.html' %}
		</div>

		<div class="details">
			<div class="links clearfix">
				<ul class="links-menu">
                <li>
                    <a href="{% url 'products:index' %}"
                        class="{% if request.resolver_match.kwargs.pk  == link.id %}
                                    active
                                  {% endif %}">
                            {{ link.name }}
                        ВСЕ</a>
                </li>

				  {% for link in category_menu %}
                    <li>
                        <a href="{% url 'products:index' link.id %}"
                           class="{% if request.resolver_match.kwargs.pk  == link.id %}
                                    active
                                  {% endif %}">
                            {{ link.name }}
                        </a>
                    </li>
                {% endfor %}
				</ul>

			</div>

            <div class="details-products">
              <div class="details-slider">
                <div class="slider-product">
                  <img width="80%" src="/media/{{ product.image }}"
                       alt="{{ product.short_desc }}">
                </div>
                <div class="slider-control">
                  <div class="block">
                    <a href="#">
                      <img width="80%" src="/media/{{ product.image }}" alt="вариант 1">
                    </a>
                  </div>
                  <div class="block">
                    <a href="#">
                      <img width="80%" src="/media/{{ product.image }}" alt="вариант 2">
                    </a>
                  </div>
                  <div class="block">
                    <a href="#">
                      <img width="80%" src="/media/{{ product.image }}" alt="вариант 3">
                    </a>
                  </div>
                </div>
              </div>

              <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <br>
                <p class="price"> {{ product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                  заказать
                  <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                  {{ product.description }}
                </div>
              </div>
            </div>



          <div class="clr"></div>
        </div>
        </div>
<div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}

templates/mainapp/products.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ titles|title }}{% endblock %}
{% block content %}
	<div class="container">
		<div class="hero-white">
			  {% include 'mainapp/menu.html' %}
		</div>

		<div class="details">
			<div class="links clearfix">
				<ul class="links-menu">
				  {% for link in category_menu %}
                    <li>
                        <a href="{% url 'products:category' link.id %}"
                           class="{% if request.resolver_match.url_name == 'categories/'%}
                                    active
                                  {% endif %}">
                            {{ link.name }}
                        </a>
                    </li>
                {% endfor %}
				</ul>

			</div>
            {% for product in products %}
			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						 <img src="/media/{{ product.image }}" width="270" alt="{{ product.short_desc }}">
					</div>

				</div>

				<div class="description">
					<h3 class="big-bold">{{product.name}}</h3>
					<h3 class="red">горячее предложение}}</h3>
					<p class="price"> {{product.price}} <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						{{product.description}}
					</div>
				</div>
			</div>
            {% endfor %}
			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="{% static 'img/product-11.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-21.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-31.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>

		<div class="clr"></div>

	</div>	

	<div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>	
{% endblock %}